version: "3"

tasks:
  build:
    desc: Build the application
    cmds:
      - go build -o ./build/cron-server{{exeExt}} .

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - ./build/cron-server{{exeExt}}
    env:
      PORT: '{{.PORT | default "8080"}}'
      SUPER_ADMIN_KEY: '{{.SUPER_ADMIN_KEY | default "super_admin_key"}}'
      CONFIG_FILE_PATH: '{{.CONFIG_FILE_PATH | default "./config/config.json"}}'
      AUTO_SAVE_INTERVAL: '{{.AUTO_SAVE_INTERVAL | default "60"}}'

  test-unit:
    desc: Run unit tests
    cmds:
      - go test -v ./...

  test-api:
    desc: Run API functionality tests
    deps: [build]
    cmds:
      - bash ./tests/test-api.sh

  test-load:
    desc: Run load tests
    deps: [build]
    cmds:
      - bash ./tests/load-test.sh

  test-error:
    desc: Run error handling tests
    deps: [build]
    cmds:
      - bash ./tests/error-test.sh

  test:
    desc: Run all tests (alias for test-all)
    cmds:
      - go test ./...

  test-all:
    desc: Run all tests (unit tests, API tests, load tests, and error tests)
    deps: [build]
    dir: tests
    cmds:
      - bash ./run-all-tests.sh > test-all.log

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f cron-server

  docker-build:
    desc: Build Docker image
    cmds:
      - docker build -t cron-server .

  docker-run:
    desc: Run Docker container
    deps: [docker-build]
    cmds:
      - >
        docker run -p {{.PORT | default "8080"}}:8080
        -e PORT=8080
        -e SUPER_ADMIN_KEY={{.SUPER_ADMIN_KEY | default "super_admin_key"}}
        -e CONFIG_FILE_PATH={{.CONFIG_FILE_PATH | default "/config/config.json"}}
        -e AUTO_SAVE_INTERVAL={{.AUTO_SAVE_INTERVAL | default "60"}}
        -v {{.PWD}}/config:/config
        cron-server

  docker-compose-up:
    desc: Run with Docker Compose
    cmds:
      - docker-compose up -d

  docker-compose-down:
    desc: Stop Docker Compose services
    cmds:
      - docker-compose down
